yarnPath: .yarn/releases/yarn-3.8.5.cjs

nodeLinker: node-modules

npmScopes:
  themenu:
    npmRegistryServer: 'https://npm.pkg.github.com/'

supportedArchitectures:
  cpu:
    - x64
    - ia32
    - arm64
  os:
    - darwin
    - linux
  libc:
    - glibc
    - musl
